[package]
name = "sps30-hdlc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
hdlc = { path = "lib/hdlc" }
serialport = { version = "4.8.1", features = ["usbportinfo-interface"] }
